name: Build Xiaomi Mi 10S (MIUI 12.0.3) (Kernel 4.19)
on:
  workflow_call:
  workflow_dispatch:
env:
  DEVICE_NAME: "xiaomi_mi10s"
  DEVICE_CODENAME: "thyme"
  CUSTOM_CMDS: "CLANG_TRIPLE=aarch64-linux-gnu- KCFLAGS=-Wno-error"
  EXTRA_CMDS: ""
  KERNEL_SOURCE: "https://github.com/PixelExperience-Devices/kernel_xiaomi_thyme.git"
  KERNEL_BRANCH: "thirteen"
  CLANG_SOURCE: "https://raw.githubusercontent.com/Neutron-Toolchains/antman/main/antman"
  CLANG_BRANCH: ""
  GCC_GNU: true
  GCC_64_SOURCE: "https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9.git"
  GCC_64_BRANCH: "android12L-release"
  GCC_32_SOURCE: "https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9.git"
  GCC_32_BRANCH: "android12L-release"
  DEFCONFIG_SOURCE: ""
  DEFCONFIG_NAME: "thyme_defconfig"
  DEFCONFIG_ORIGIN_IMAGE: ""
  DEFCONFIG_FROM_BOOT: false
  KERNELSU_SOURCE: ""
  KERNELSU_BRANCH: ""
  KERNELSU_AUTO_GET: "true"
  KERNELSU_AUTO_FORK: "resukisu"
  SUSFS_ENABLE: true
  SUSFS_FIXED: true
  AK3_SOURCE: "https://github.com/osm0sis/AnyKernel3.git"
  AK3_BRANCH: "master"
  BOOT_SOURCE: ""
  NEED_DTBO: false
  NEED_SAFE_DTBO: false
  ROM_TEXT: "miui12.0.3_a11"
  PYTHON_VERSION: "3"
  PACK_METHOD: "Anykernel3"
  PACK_KMODULES: "false"
  KERNELSU_METHOD: "shell"
  PATCHES_SOURCE: "JackA1ltman/NonGKI_Kernel_Patches"
  PATCHES_BRANCH: "mi_kernel"
  SUSFS_FOLDER_FIXED: ""
  SUSFS_PATCH_FIXED: ""
  REKERNEL_ENABLE: "false"
  HOOK_METHOD: "syscall"
  KERNEL_PATCH: "false"
  KPM_ENABLE: "false"
  KPM_INLINE: "false"
  KPM_KPATCH_NEXT: "false"
  KPM_PATCH_SOURCE: "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU_patch/refs/heads/main/kpm/patch_linux"
  BASEBAND_GUARD_ENABLE: "false"
  BASEBAND_GUARD_BOOT: "false"
  GENERATE_DTB: "false"
  GENERATE_CHIP: "qcom"
  BUILD_DEBUGGER: "true"
  SKIP_PATCH: "true"
  BUILD_OTHER_CONFIG: "false"
  MERGE_CONFIG_FILES: ""
  FREE_MORE_SPACE: "false"
jobs:
  build-kernel:
    name: Xiaomi Mi 10S (MIUI 12.0.3) (Kernel 4.19)
    runs-on: ubuntu-latest
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_HARDLINK: "true"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Compilation environment preparation
        uses: ./.github/workflows/build-env
      - name: Get necessary tools
        uses: ./.github/workflows/build-ready
      - name: Patch Kernel of SUSFS
        uses: ./.github/workflows/patch-susfs
      - name: Patch for no-kprobe
        uses: ./.github/workflows/patch-no-kprobe
      - name: Patch Kernel of ReKernel
        uses: ./.github/workflows/patch-rekernel
      - name: Patch Kernel of Baseband Guard
        uses: ./.github/workflows/patch-baseband-guard
      - name: Fix kernel strict-prototypes and implicit-int
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE/device_kernel
          sed -i 's/^struct device \*getDev()$/struct device *getDev(void)/' drivers/input/touchscreen/fts_521/fts_lib/ftsIO.c
          sed -i 's/^struct i2c_client \*getClient()$/struct i2c_client *getClient(void)/' drivers/input/touchscreen/fts_521/fts_lib/ftsIO.c
          sed -i 's/^static u8 goodix_panel_color_read()$/static u8 goodix_panel_color_read(void)/' drivers/input/touchscreen/goodix_driver_gt9886/goodix_ts_core.c
          sed -i 's/^static u8 goodix_panel_vendor_read()$/static u8 goodix_panel_vendor_read(void)/' drivers/input/touchscreen/goodix_driver_gt9886/goodix_ts_core.c
          sed -i 's/^static u8 goodix_panel_display_read()$/static u8 goodix_panel_display_read(void)/' drivers/input/touchscreen/goodix_driver_gt9886/goodix_ts_core.c
          sed -i 's/^struct class \*get_xiaomi_touch_class()$/struct class *get_xiaomi_touch_class(void)/' drivers/input/touchscreen/xiaomi/xiaomi_touch.c
          sed -i 's/^struct device \*get_xiaomi_touch_dev()$/struct device *get_xiaomi_touch_dev(void)/' drivers/input/touchscreen/xiaomi/xiaomi_touch.c
          sed -i 's/^static hdl_count = 0;$/static int hdl_count = 0;/' techpack/camera/drivers/cam_req_mgr/cam_req_mgr_util.c
          sed -i 's/^struct ce_ops \*ce_services_srng()$/struct ce_ops *ce_services_srng(void)/' drivers/staging/qca-wifi-host-cmn/hif/src/ce/ce_service_srng.c
          sed -i 's/^static int rmnet_perf_notify()$/static int rmnet_perf_notify(void)/' techpack/data/drivers/rmnet/perf/rmnet_perf_opt.c
          sed -i 's/^rmnet_perf_free_hash_table()$/rmnet_perf_free_hash_table(void)/' techpack/data/drivers/rmnet/perf/rmnet_perf_opt.c
          sed -i 's/^struct target_if_ctx \*target_if_get_ctx()$/struct target_if_ctx *target_if_get_ctx(void)/' drivers/staging/qca-wifi-host-cmn/target_if/core/src/target_if_main.c
      - name: Fix python2 for dtbo.img
        run: |
          sudo sh -c 'echo "#!/bin/sh\nexec python3 \"\$@\"" > /usr/bin/python2 && chmod +x /usr/bin/python2'
          cd $GITHUB_WORKSPACE/device_kernel
          sed -i 's/xrange/range/g' scripts/dtc/mkdtboimg.py
      - name: Build Process
        uses: ./.github/workflows/build-process
      - name: Pack Process
        uses: ./.github/workflows/pack-process
      - name: Upload Artifacts
        uses: ./.github/workflows/upload-files
